// AUTO-GENERATED by wayland CLI from brief: wayland-co
// DO NOT EDIT THIS FILE DIRECTLY.
// Changes here will be overwritten on the next scaffold.
// To update content, edit the brief JSON and re-run:
//   wayland scaffold --brief <path> --force

export type SectionCopyEntry = {
  eyebrow?: string;
  heading?: string;
  subhead?: string;
};

export type SectionCopy = {
  serviceGrid?: SectionCopyEntry;
  testimonials?: SectionCopyEntry;
  about?: SectionCopyEntry;
};

export type Business = {
  name: string;
  tagline: string;
  description: string;
  phone: string;
  email: string;
  address: string;
  hours: string;
  portraitUrl?: string;
  logoUrl?: string;
};

export type PortfolioItem = {
  title: string;
  category?: string;
  imageUrl: string;
  href?: string;
  description?: string;
};

export type Portfolio = readonly PortfolioItem[];

export type TeamMember = {
  name: string;
  role: string;
  bio: string;
  photoUrl?: string;
};

export type Team = readonly TeamMember[];

export type FaqEntry = { q: string; a: string };

export type Faq = readonly FaqEntry[];

export type Testimonial = { quote: string; author: string; role: string; company: string };

export type Testimonials = readonly Testimonial[];

export type Service = {
  name: string;
  shortDesc: string;
  longDesc: string;
  icon: string;
  /**
   * Optional per-service image (design-range field). A local path such as
   * /images/foo.jpg or a full URL. Omitted when the brief supplies no
   * per-service photo (see briefs/schema/brief.schema.ts -> serviceSchema).
   */
  imageUrl?: string;
};

export type Services = readonly Service[];

export type Tier = 'foundation' | 'operator' | 'engine';

export type Archetype = 'service';

const tier: Tier = "operator";

const archetype: Archetype = "service";

const sectionCopy: SectionCopy = {};

const services: Services = [
  {
    "name": "Express",
    "shortDesc": "A modern site, live in days — and you own it.",
    "longDesc": "A fast, mobile, modern website with booking, contact, and analytics wired up — launched in days and handed off. No retainer, no lock-in. The fastest way to stop looking dated.",
    "icon": "zap",
    "imageUrl": "/images/express.jpg"
  },
  {
    "name": "Foundation",
    "shortDesc": "Look current. Get found. Get booked.",
    "longDesc": "A refined site built to get you discovered on Google and turn visitors into booked appointments, with a managed care plan so it stays fast, secure, and current.",
    "icon": "layout-template",
    "imageUrl": "/images/foundation.jpg"
  },
  {
    "name": "Operator",
    "shortDesc": "Your front office, handled.",
    "longDesc": "Everything in Foundation plus a managed operations layer — a CRM, online booking, and instant lead capture so no inquiry slips through, with follow-up handled for you. Your front office, off your plate.",
    "icon": "workflow",
    "imageUrl": "/images/operator.jpg"
  },
  {
    "name": "Engine",
    "shortDesc": "An AI marketing team for a part-timer's price.",
    "longDesc": "Everything in Operator plus ongoing AI-drafted content, SEO, and lead generation — a growth engine that keeps you visible and booked, managed end to end.",
    "icon": "rocket",
    "imageUrl": "/images/engine.jpg"
  }
];

const business: Business = {
  "name": "Wayland & Co.",
  "tagline": "Bringing Main Street into the AI era.",
  "description": "Wayland & Co. modernizes local service businesses with a fast website plus AI-powered booking, follow-up, and content — so a small team competes like it has a full digital department.",
  "phone": "(401) 484-8671",
  "email": "hello@waylandandco.com",
  "address": "Providence, RI",
  "hours": "By appointment",
  "logoUrl": "/images/wayland-logo.png"
};

const portfolio: Portfolio = [];

const team: Team = [];

const faq: Faq = [
  {
    "q": "How fast can my site be live?",
    "a": "Express sites go live in days; fuller builds typically land within a week or two."
  },
  {
    "q": "Do I own my website?",
    "a": "Yes — always. Your site, domain, content, and data are yours, with no lock-in. Month-to-month on managed plans, cancel anytime."
  },
  {
    "q": "What does it cost?",
    "a": "From a one-time Express build to a fully managed monthly system — pricing scales with what you need. We'll give you a clear quote on a quick call."
  },
  {
    "q": "What's the “AI” part?",
    "a": "Under the hood we use AI to draft your content and speed up the build — so a small team gets big-company capability."
  },
  {
    "q": "What if I don't love it?",
    "a": "We'll rebuild it, free, until you do. And if your site ever feels dated on a managed plan, we refresh it on us."
  }
];

const testimonials: Testimonials = [];

export const content = {
  tier,
  archetype,
  business,
  hero: {
  "headline": "Bring your business into the AI era.",
  "subhead": "We modernize local businesses with a fast website, online booking, instant lead capture, and AI-drafted content — so you compete like you've got a full digital team, without hiring one.",
  "ctaPrimary": {
    "label": "Book a call",
    "href": "/contact"
  },
  "ctaSecondary": {
    "label": "See how it works",
    "href": "/services"
  },
  "imageUrl": "/images/hero.jpg"
},
  services,
  about: {
  "body": "Most local businesses are running on 2015 tech — a dated site, phone-tag booking, leads that slip away. Wayland & Co. fixes that. We stand up a modern website with online booking, instant lead capture, and AI-drafted content — built fast on the same tools the big players use — and can keep it running for you month to month. You get the output of a full digital team without hiring one, so you can stay focused on the work you do best.",
  "values": [
    {
      "title": "You own everything",
      "body": "Your site, domain, content, and data are always yours — no lock-in, ever."
    },
    {
      "title": "Modern by default",
      "body": "Fast, mobile, and built on current tech — never a dated, off-the-shelf template."
    },
    {
      "title": "Built fast, run for you",
      "body": "Live in days, then optionally managed monthly so you never have to touch it."
    },
    {
      "title": "AI under the hood",
      "body": "We point the same AI tools the big players use at Main Street businesses."
    }
  ]
},
  faq,
  testimonials,
  cta: {
  "heading": "Ready to modernize?",
  "subhead": "Book a 20-minute call and we'll map your AI-era upgrade — no pressure, no jargon.",
  "button": {
    "label": "Book a call",
    "href": "/contact"
  }
},
  bento: [],
  portfolio,
  team,
  sectionCopy,
  componentVariants: {
  "hero": "split",
  "serviceGrid": "cards",
  "testimonials": "default",
  "cta": "default",
  "about": "body"
},
} as const;

export type Content = typeof content;
