// SOURCE OF TRUTH for brand-level theming.
// Generated by Wayland CLI from brief.brand. Do not edit by hand.

export const theme = {
  colors: {
    primary: '#4338CA',
    primaryFg: '#FFFFFF',
    accent: '#F59E0B',
    accentFg: '#1E293B',
    background: '#FFFFFF',
    foreground: '#0F172A',
    muted: '#F1F5F9',
    mutedFg: '#64748B',
    border: '#E2E8F0',
  },
  fonts: {
    heading: 'Plus Jakarta Sans, system-ui, sans-serif',
    body: 'Inter, system-ui, sans-serif',
  },
  radii: {
    sm: '0.25rem',
    md: '0.5rem',
    lg: '0.75rem',
  },
} as const;

export type Theme = typeof theme;
